name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: Plataforma_Gestion_Inventario
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VITE_API_URL: http://127.0.0.1:8000/api
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/Plataforma_Gestion_Inventario

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Django tests with Coverage
        run: |
          python manage.py migrate
          coverage run manage.py test
          coverage report

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test
